name: Java CI with Gradle
##############################
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  depCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@6.0.5
        with:
          arguments: dependencyCheckAnalyze
      - name: Backup JSON Report
        if: "${{ always() }}"
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report.json
          path: ./build/reports/dependency-check-report.json

  owasp_report:
    needs: [depCheck]
    if: "${{ always() }}"
    runs-on: ubuntu-20.04
    name: Create a report with an overview of the vulnerabilities per dependency
    steps:
      - uses: actions/checkout@v2
        with:
          repository: perpk/owasp-report-custom-render
      - uses: actions/download-artifact@v2
        with:
          name: dependency-check-report.json
          path: ./
      - name: Perform npm install on checked-out action
        run: npm install
      - name: Run Report Creation
        uses: ./
        with:
          owasp-json-report: dependency-check-report.json
      - name: Upload overview report
        uses: actions/upload-artifact@v2
        with:
          name: Owasp Overview Report
          path: owasp-report-overview.pdf
